# Generated by Django 4.2.4 on 2023-11-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
